pluginManagement {
    repositories {
        maven {
            name = 'WorkspaceOffline'
            url = uri('../.gradle-offline-repo')
        }
        maven {
            name = 'WorkspaceMaven'
            url = uri('../.m2/repository')
        }
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.neoforged.moddev') {
                useModule("net.neoforged:moddev-gradle:${requested.version}")
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven {
            name = 'WorkspaceOffline'
            url = uri('../.gradle-offline-repo')
            metadataSources {
                gradleMetadata()
                mavenPom()
                artifact()
            }
        }
        maven {
            name = 'WorkspaceMaven'
            url = uri('../.m2/repository')
            metadataSources {
                mavenPom()
                artifact()
            }
        }
        mavenCentral()
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'NeoForgeMojangMeta'
            url = 'https://maven.neoforged.net/mojang-meta'
        }
    }
}

rootProject.name = 'ForgeDash'
